// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBfH8vf38sSFiBxEhvWyYWHqOrMmpChZE',
    appId: '1:444752871044:web:7f0fb72d5cd10361f40cd1',
    messagingSenderId: '444752871044',
    projectId: 'interview-512ac',
    authDomain: 'interview-512ac.firebaseapp.com',
    storageBucket: 'interview-512ac.appspot.com',
    measurementId: 'G-MVGQCPVVNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxeSD-wuOMELG9n9CV8ZFylechoB7088s',
    appId: '1:444752871044:android:ebc217f7db9f482cf40cd1',
    messagingSenderId: '444752871044',
    projectId: 'interview-512ac',
    storageBucket: 'interview-512ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClVX9CKl67bZ-mdDCWPGbTm4gdZHkhl54',
    appId: '1:444752871044:ios:3e80a3302dad149af40cd1',
    messagingSenderId: '444752871044',
    projectId: 'interview-512ac',
    storageBucket: 'interview-512ac.appspot.com',
    iosBundleId: 'com.example.caretutorsTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClVX9CKl67bZ-mdDCWPGbTm4gdZHkhl54',
    appId: '1:444752871044:ios:2390b614b7438c86f40cd1',
    messagingSenderId: '444752871044',
    projectId: 'interview-512ac',
    storageBucket: 'interview-512ac.appspot.com',
    iosBundleId: 'com.example.caretutorsTodo.RunnerTests',
  );
}
